sampler:
  test_list_path: test_lists/mos_test.json
  sample_size_per_test: 10
gradio:
  server_name: 127.0.0.1
  server_port: 52705
  root_path: /mos
  share: false
  show_error: true
  allowed_paths:
    - cwd
attention_checks:

instructions:

language: english

hydra:
  run:
    dir: ./test_${language}/${now:%Y-%m-%d}/${now:%H-%M-%S}
